-- 0014_banners.sql
-- 배너 관리 테이블 생성
CREATE TABLE IF NOT EXISTS `banners` (
  `id`        INT AUTO_INCREMENT PRIMARY KEY,
  `name`      VARCHAR(200) NOT NULL,
  `imageUrl`  VARCHAR(500) NOT NULL,
  `linkUrl`   VARCHAR(500),
  `note`      TEXT,
  `isActive`  BOOLEAN NOT NULL DEFAULT TRUE,
  `sortOrder` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
